### ISSUE TITLE
unhandled perf error when running on raspi

### ISSUE THREAD

**Issue by jancajthaml** [jancajthaml-openbank/e2e#62]
```
  debug | starting
  debug | asserting empty journal, logs and metrics
   info | start tests
  debug | waiting until everyone is ready
          eventually_ready took 3 s 136 ms
   info | preparing creation of 5000 account for tenant otz336ywho
   info | preparing creation of 5000 account for tenant q29hoz0imz
   info | preparing creation of 5000 account for tenant 89vk7f7b0d
   info | preparing creation of 5000 account for tenant 7x26dp43qd
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:845: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
   warn | 19972 accounts created, 28 failed                             
          random_uniform_accounts(_, 20000) took 4 m 39 s
  debug | waiting until everyone is ready
          eventually_ready took 3 s 270 ms
   info | preparing creation of 100 account for tenant 8sltf329fr
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:845: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
   pass | all passed                                                      
          random_uniform_accounts(_, 100) took 1 s 487 ms
   info | prepared checking balance of 100 accounts
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:845: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
   pass | all passed                                                      
          check_balances(_) took 1 s 364 ms
          get accounts scenario took 8 s 959 ms
          new accounts scenario took 4 m 58 s
Traceback (most recent call last):
  File "/usr/local/etc/e2e/perf/systemd/search.py", line 30, in restart
    subprocess.check_call(["systemctl", "restart", 'search'], stdout=Unit.FNULL, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['systemctl', 'restart', 'search']' returned non-zero exit status 5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/etc/e2e/perf/main.py", line 125, in main
    manager.reset()
  File "/usr/local/etc/e2e/perf/appliance_manager.py", line 63, in reset
    node.restart()
  File "/usr/local/etc/e2e/perf/systemd/search.py", line 32, in restart
    raise RuntimeError("Failed to restart search with error {0}".format(ex))
RuntimeError: Failed to restart search with error Command '['systemctl', 'restart', 'search']' returned non-zero exit status 5

  debug | gracefull teardown components
  debug | terminated
          test run took 4 m 59 s
````

**Comment by jancajthaml** [comment]
INFO:

- search is not installed on raspi due to mongodb mirror problem
