### ISSUE TITLE
http 504 timeout flake

### ISSUE THREAD

**Issue by jancajthaml** [jancajthaml-openbank/e2e#69]
https://circleci.com/gh/jancajthaml-openbank/e2e/97446

```
 1) Transaction workflow tenant isolation When pasive CZK account FIO/Nostro is created -> And active CZK account FIO/Credit is created -> Then FIO/Nostro should exist -> And FIO/Credit should exist -> Then RAIFFEISEN/Nostro should not exist -> And RAIFFEISEN/Credit should not exist -> When pasive CZK account RAIFFEISEN/Nostro is created -> And active CZK account RAIFFEISEN/Credit is created -> Then RAIFFEISEN/Nostro should exist -> And RAIFFEISEN/Credit should exist -> When 1 CZK is transfered from Nostro to Credit for tenant FIO -> Then FIO/Nostro balance should be -1 CZK -> Then FIO/Credit balance should be 1 CZK -> Then RAIFFEISEN/Nostro balance should be 0 CZK -> Then RAIFFEISEN/Nostro balance should be 0 CZK
     Failure/Error: Then  RAIFFEISEN/Nostro should not exist
     
       expected: 404
            got: 504
     
       (compared using ==)
     # ./steps/vault_steps.rb:63:in `block in <top (required)>'
     # ./features/transaction.feature:31:in `run_step'
     # ./features/transaction.feature:27:in `block (4 levels) in run_feature'
     # ./features/transaction.feature:26:in `each'
     # ./features/transaction.feature:26:in `block (3 levels) in run_feature'
     # ./features/transaction.feature:31:in `RAIFFEISEN/Nostro should not exist'
```

**Comment by jancajthaml** [comment]
https://circleci.com/gh/jancajthaml-openbank/e2e/101563

```
  1) Search API test Transactions query When active EUR account SEARCH/Credit is created -> And pasive EUR account SEARCH/Debit is created -> And 1 EUR is transfered from Debit to Credit for tenant SEARCH -> When I request search -> Then search responds with 200
     Failure/Error: When  active EUR account SEARCH/Credit is created
       expected 504 to satisfy expression `x == 200 || x == 409`
     # ./steps/vault_steps.rb:22:in `block in <top (required)>'
     # ./features/search_api.feature:37:in `run_step'
     # ./features/search_api.feature:38:in `block (4 levels) in run_feature'
     # ./features/search_api.feature:37:in `each'
     # ./features/search_api.feature:37:in `block (3 levels) in run_feature'
     # ./features/search_api.feature:37:in `active EUR account SEARCH/Credit is created'
```
